### ISSUE TITLE
适配手机版

### ISSUE THREAD

**Issue by wnbh** [jdysya/pikpakHelpr-plus#1]
希望适配一下手机版，使用kiwi浏览器运行脚本，弹窗视图过大，无法操作

**Comment by jdysya** [comment]
手机上还能用aria2吗，我暂时没有这个需求，建议使用电脑，而且手机有客户端呀，支持批量下载来着

**Comment by jdysya** [comment]
不过这个视图过大的情况有时间我会调整一下

**Comment by wnbh** [comment]
> 不过这个视图过大的情况有时间我会调整一下

因为我手机用的多一些，也有推送到远程服务器的需求，并不是在手机上用aria2，当然手机上确实可以用aria2，但我主要是推送到远程服务器

**Comment by jdysya** [comment]
7c7f5259e32b25768483a00414e5b22e20740044 已优化在小屏幕上的显示，新版本已上传：https://greasyfork.org/zh-CN/scripts/503530-pikpak%E5%8A%A9%E6%89%8Bplus
